name: influxdb
version: '1.0.0'
summary: Scalable datastore for metrics, events, and real-time analytics
description: |
  InfluxDB is an open source time series database with no external
  dependencies. It's useful for recording metrics, events, and performing
  analytics.
  .
  Features
  .
   - Built-in HTTP API so you don't have to write any server side code to get
     up and running.
   - Data can be tagged, allowing very flexible querying.
   - SQL-like query language.
   - Simple to install and manage, and fast to get data in and out.
   - It aims to answer queries in real-time. That means every data point is
     indexed as it comes in and is immediately available in queries that
     should return in < 100ms.

grade: stable
confinement: devmode

apps:
  influxdb:
    command: usr/bin/influxd
    daemon: simple
    plugs: [network, network-bind]

parts:
  influxdb:
    source: https://dl.influxdata.com/influxdb/releases/influxdb-1.0.0_linux_amd64.tar.gz
    plugin: dump
